- name: Install web server
  package:
    name: httpd
    state: installed
    
- name: Copy abc.txt file
  copy:
    src: abc.txt
    dest: /tmp/abc.txt

- name: Print fruit name
  debug:
    msg: "FRUIT NAME = {{FRUIT}} "